version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "ci(github-actions): "
    labels:
      - "ci"
    assignees:
      - "hakadoriyaco"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "build(go): "
    labels:
      - "build"
    assignees:
      - "hakadoriyaco"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/grpcz/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "build(go): "
    labels:
      - "build"
    assignees:
      - "hakadoriyaco"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/otelz/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "build(go): "
    labels:
      - "build"
    assignees:
      - "hakadoriyaco"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/xz/toolz/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "build(go): "
    labels:
      - "build"
    assignees:
      - "hakadoriyaco"
    groups:
      dependencies:
        patterns:
          - "*"
