version: "2"
run:
  modules-download-mode: readonly
  allow-parallel-runners: true
linters:
  # ref. https://golangci-lint.run/usage/linters/
  default: all
  disable:
    - depguard # unnecessary
    - dupl # unnecessary
    - goconst # unnecessary
    - godot # unnecessary
    - godox # unnecessary
    - interfacebloat # unnecessary
    - ireturn # NOTE: too many false positives and negatives occur frequently, causing the --fix option to malfunction. So it is disabled.
    - lll # unnecessary
    - nlreturn # ignore "return with no blank line before"
    - nonamedreturns # unnecessary
    - varnamelen # unnecessary
    - wsl # ignore "declarations should never be cuddled"
  settings:
    wrapcheck:
      ignore-sigs:
        - func errors.New(text string) error
        - func fmt.Errorf(format string, a ...any) error
        - func fmt.Errorf(format string, a ...interface{}) error
        - func github.com/hakadoriya/z.go/errorz.Errorf(format string, a ...interface{}) error
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - canonicalheader
          - containedctx
          - cyclop
          - dupl
          - dupword
          - err113
          - exhaustruct
          - forcetypeassert
          - funlen
          - gochecknoglobals
          - gocognit
          - goconst
          - gocyclo
          - gosec
          - maintidx
          - noctx
          - revive
          - staticcheck
          - testpackage
          - unused
          - varnamelen
          - wrapcheck
        path: (.*_test\.go|/example/.*\.go)
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/hakadoriya/z.go
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
