name: task-list-checker

on:
  pull_request:
    types:
      - opened
      - edited
      - ready_for_review
      - reopened
      - synchronize

jobs:
  task-list-checker:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: hakadoriya/github-actions-task-list-checker@v0.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
